version: '3'

services:
  db:
    image: postgres:9.6.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - localnet
  
  redis:
    image: "redis:alpine"
    networks:
      - localnet
  nginx:
    image: nginx:latest
    links:
      - web:uwsgi
    ports:
      - "8080:8080"
    depends_on:
      - web
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - localnet
  web:
    build: .
    command: bash -c "python /code/manage.py collectstatic --noinput && python /code/manage.py migrate --noinput && uwsgi --ini /code/config/uwsgi.ini"
    volumes:
      - .:/code
      - media-volume:/www/var/media
    ports:
      - "8081"
    depends_on:
      - db
      - redis
    networks:
      - localnet
  
  celery:
    build: .
    command: celery -A pdf_service worker -l info
    volumes:
      - .:/code
      - media-volume:/www/var/media
    depends_on:
      - web
    networks:
      - localnet

volumes:
  postgres_data:
  media-volume:

networks:
  localnet:
