# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=4096, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.URLField(blank=True, max_length=4096, null=True)),
                ('alive', models.NullBooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='urls',
            field=models.ManyToManyField(related_name='documents', to='pdf_app.Url'),
        ),
    ]
